const mongoose = require("mongoose");

// Records every change worth defending later: weight edits, progress
// changes, approvals/rejections, and anything self-healing quietly fixed.
// Needs to answer "who changed this, when, and what was it before" months
// later, so rows are append-only, never edited or deleted.
const okrAuditLogSchema = new mongoose.Schema(
  {
    // Who did it. Null for entries generated by background repair work.
    actor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // Machine-readable event name, e.g. "keyresult.weight.changed".
    action: {
      type: String,
      required: true,
      index: true,
    },

    // What was touched. entityType is the collection, entityId the document.
    entityType: {
      type: String,
      enum: ["objective", "keyresult", "checkin", "calendar-link", "system"],
      required: true,
    },
    entityId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },

    // The objective this change ultimately affects, so we can pull the whole
    // history for one goal in a single query.
    objective: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "OkrObjective",
      default: null,
      index: true,
    },

    // Before/after values. Kept loose on purpose: a weight change stores
    // numbers, an approval stores strings, a repair stores ids.
    before: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    after: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // A plain-English sentence for the audit view.
    message: {
      type: String,
      required: true,
      maxlength: 500,
    },

    // info = ordinary activity, repair = self-healing fixed something,
    // warning = something worth a look.
    severity: {
      type: String,
      enum: ["info", "repair", "warning"],
      default: "info",
    },
  },
  {
    timestamps: true,
  }
);

// Audit screen reads newest first.
okrAuditLogSchema.index({ createdAt: -1 });

// An audit entry that can be rewritten isn't really an audit entry, so block
// every way Mongoose lets you change or remove a document. Deletes have one
// escape hatch for real retention jobs/test cleanup: pass
// { allowAuditPurge: true } on purpose, so nothing gets wiped by accident.

function refuseEdit(next) {
  next(new Error("Audit log entries cannot be modified once written"));
}

function refuseDelete(next) {
  const options = typeof this.getOptions === "function" ? this.getOptions() : {};
  if (options && options.allowAuditPurge === true) {
    return next();
  }
  next(
    new Error(
      "Audit log entries cannot be deleted. Pass { allowAuditPurge: true } if this is an intentional retention purge."
    )
  );
}

okrAuditLogSchema.pre("updateOne", refuseEdit);
okrAuditLogSchema.pre("updateMany", refuseEdit);
okrAuditLogSchema.pre("findOneAndUpdate", refuseEdit);
okrAuditLogSchema.pre("deleteOne", refuseDelete);
okrAuditLogSchema.pre("deleteMany", refuseDelete);
okrAuditLogSchema.pre("findOneAndDelete", refuseDelete);

// Saving over an existing doc counts as an edit too. Brand new ones are fine.
okrAuditLogSchema.pre("save", function guardSave(next) {
  if (!this.isNew) {
    return next(new Error("Audit log entries cannot be modified once written"));
  }
  next();
});

module.exports = mongoose.model("OkrAuditLog", okrAuditLogSchema);
